# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# Maven

 

resources:

  pipelines:

    - pipeline: binaries

      source: "CI - Binaries"

      trigger:

        enabled: true

        branches:

          include:
          
            - Release

            - develop
trigger:


    branches:

        include:

        - main

       

    paths:

        include:

        - '*' # same as '/' for the repository root

 

pool:

  vmImage: 'windows-latest'

 

steps:

- task: Maven@3

  inputs:

    mavenPomFile: 'pom.xml'

    mavenOptions: '-Xmx3072m'

    javaHomeOption: 'JDKVersion'

    jdkVersionOption: '1.11'

    jdkArchitectureOption: 'x64'

    publishJUnitResults: true

    checkStyleRunAnalysis: false

    testResultsFiles: '**/TEST-*.xml'

    goals: 'clean install'

 

- task: PublishTestResults@2

  inputs:

    testResultsFormat: 'JUnit'

    testResultsFiles: '**/TEST-*.xml'




